import { Skill } from '../types';

export const SKILLS: Skill[] = [
  // Programming Languages
  { name: 'python', category: 'programming language' },
  { name: 'java', category: 'programming language' },
  { name: 'javascript', category: 'programming language' },
  { name: 'html', category: 'programming language' },
  { name: 'css', category: 'programming language' },
  { name: 'sql', category: 'programming language' },
  { name: 'c', category: 'programming language' },
  { name: 'c++', category: 'programming language' },
  { name: 'c#', category: 'programming language' },
  { name: 'ruby', category: 'programming language' },
  { name: 'swift', category: 'programming language' },
  { name: 'php', category: 'programming language' },
  { name: 'rest', category: 'programming language' },
  { name: 'go', category: 'programming language' },
  { name: 'typescript', category: 'programming language' },
  { name: 'scala', category: 'programming language' },
  { name: 'kotlin', category: 'programming language' },
  { name: 'rust', category: 'programming language' },
  { name: 'elixir', category: 'programming language' },
  { name: 'haskell', category: 'programming language' },
  { name: 'lua', category: 'programming language' },
  { name: 'clojure', category: 'programming language' },
  { name: 'groovy', category: 'programming language' },
  { name: 'dart', category: 'programming language' },
  { name: 'perl', category: 'programming language' },
  { name: 'bash', category: 'programming language' },
  { name: 'powershell', category: 'programming language' },
  { name: 'r', category: 'programming language' },
  { name: 'matlab', category: 'programming language' },
  { name: 'graphql', category: 'programming language' },
  { name: 'react', category: 'framework' },
  { name: 'angular', category: 'framework' },
  { name: 'vue', category: 'framework' },
  { name: 'django', category: 'framework' },
  { name: 'flask', category: 'framework' },
  { name: 'spring', category: 'framework' },
  { name: 'express', category: 'framework' },
  { name: 'rails', category: 'framework' },
  { name: 'tensorflow', category: 'framework' },
  { name: 'pytorch', category: 'framework' },
  { name: 'hadoop', category: 'framework' },
  { name: 'spark', category: 'framework' },
  { name: 'hive', category: 'framework' },
  { name: 'webpack', category: 'framework' },
  { name: 'junit', category: 'framework' },
  { name: 'pytest', category: 'framework' },
  { name: 'mocha', category: 'framework' },
  { name: 'chai', category: 'framework' },
  { name: 'log4j', category: 'framework' },
  { name: 'selenium', category: 'framework' },
  { name: 'react-native', category: 'framework' },

  // Software
  { name: 'linux', category: 'software' },
  { name: 'git', category: 'software' },
  { name: 'npm', category: 'software' },
  { name: 'yarn', category: 'software' },
  { name: 'postman', category: 'software' },
  { name: 'jenkins', category: 'software' },
  { name: 'jira', category: 'software' },
  { name: 'trello', category: 'software' },
  { name: 'vscode', category: 'software' },
  { name: 'intellij', category: 'software' },
  { name: 'eclipse', category: 'software' },
  { name: 'mysql', category: 'software' },
  { name: 'postgresql', category: 'software' },
  { name: 'sqlite', category: 'software' },
  { name: 'oracle', category: 'software' },
  { name: 'firebase', category: 'software' },
  { name: 'aws cli', category: 'software' },
  { name: 'gimp', category: 'software' },
  { name: 'figma', category: 'software' },

  // Soft Skills
  { name: 'communication', category: 'softskills' },
  { name: 'teamwork', category: 'softskills' },
  { name: 'problem-solving', category: 'softskills' },
  { name: 'critical-thinking', category: 'softskills' },
  { name: 'time-management', category: 'softskills' },
  { name: 'leadership', category: 'softskills' },
  { name: 'agile', category: 'softskills' },
  { name: 'scrum', category: 'softskills' },
  { name: 'mentoring', category: 'softskills' },
  { name: 'adaptability', category: 'softskills' },

  // Infrastructure
  { name: 'docker', category: 'infrastructure' },
  { name: 'kubernetes', category: 'infrastructure' },
  { name: 'jenkins', category: 'infrastructure' },
  { name: 'ansible', category: 'infrastructure' },
  { name: 'terraform', category: 'infrastructure' },
  { name: 'aws', category: 'infrastructure' },
  { name: 'azure', category: 'infrastructure' },
  { name: 'gcp', category: 'infrastructure' },
  { name: 'prometheus', category: 'infrastructure' },
  { name: 'grafana', category: 'infrastructure' },
  { name: 'lambda', category: 'infrastructure' },
  { name: 'cloudwatch', category: 'infrastructure' },
  { name: 'sns', category: 'infrastructure' },
  { name: 'sqs', category: 'infrastructure' },
  { name: 'api gateway', category: 'infrastructure' },
];
